# Tasks
***

These are my solutions to the Tasks assesment to be completed as part of my Emerging Technologies module. Author Keith Nolan.
Email: (g00351932@gmit.ie)

***

# Task 1


The first of these tasks is to write a Python function called sqrt2.
Thich calculates and prints to the screen the square root of 2 to 100 decimal places.
Below is my solution.


***

### Task: Calculate a sqaure root
***

The sqaure root of a number can be calculated using Newton's Method. [1]

To find the sqaure root $z$ of a number $x$, we can iterate using the following equation.

Add in how it works

$$ z' = z - \frac{z^2 - x}{2z} $$

[1] A tour of go. Exercise: Loops and Functions https://tour.golang.com/flowcontrol/8

In [10]:
def sqrt2(x):
    """ 
    function to calculate the sqaure root of 2 to 100 decimal places
    """
    #initial guess for the square root of z
    z = x / 2
    #loop until we're happy with the accuracy
    while abs(x -(z * z)) > 0.0001:
        #calculate a better guess for the square root
        z -= (z*z - x) / (2*z)
    #Return the approximate square root of 2
    
    return print("%.100f" % z)


#### Testing the above function

In [12]:
#Testing the above function
sqrt2(2)

1.4142156862745098866440685014822520315647125244140625000000000000000000000000000000000000000000000000


#### Testing the function on 2 using the math.sqrt function
Below the above function is being tested with some known values

In [17]:
import math
math.sqrt(2)

1.4142135623730951

# Task 2
Chi-squared test for independence
****


The goal of this task is to use scipy.stats to verify this value and calculate the associated p value.
***

In [43]:
import scipy.stats as stats

obs =[[90, 60, 104, 95], [30, 50, 51, 20],[30, 40, 45, 35]]

g, p, dof, expctd = chi2_contingency(obs)


#chi2_contingency(obs)
print(p)
print(dof)
print(g)
print(expctd)

0.0004098425861096696
6
24.5712028585826
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


****

# Task 3
Standard deviation

*****

The goals of this task are:
- to research the Excel functions STDDEV.P and STDDEV.S and explain their differences
- use numpy to perform a simulation demonstrating that the STDDEV.S calculation is a better estimate for the standard deviation of a population when performed on a sample.

#### STDDEV.P
<b>STDDEV.P</b> is used to calculate the standard deviation of a whole population. The p in STDDEV stands for population. For example if you had a set of data that contains all of the members of some specified group. A population could be <b>ALL</b> of the people studying in your college. 

The formula we use for <b> standard deviation for a population</b> is:

$$ \sigma x = \sqrt \frac {1}{n} \sum \limits_{i=1}  ^{n} ( x_i - \bar x )^2$$
***

<b>Mean absolute deviation</b>
The mean absolute deviation of a dataset is the average distance between each data point and the mean.

Below is the formula to calculate the <b>Mean Absolute Variance of a Population</b>

$$Population (MAD)= \frac{1}{n} \sum \limits_{i=1}  ^{n}| x_i - \bar x $$
***
#### STDDEV.S
<b>STDDEV.S</b> is used when you have a sample of a dataset such as a sample of a population. For example if you wanted to find some of the students in your college who identify as female. This would be used to generalise this dample to the entire popuation. The sample will then be used as an estimate of the entire population.

The formula we use for standard deviation on a <b>sample of a population</b> is:
$$ S x = \sqrt \frac {1}{n -1} \sum \limits_{i=1}  ^{n} ( x_i - \bar x )^2$$


Below is the equation to calculate the <b>Mean Absolute Variance of a sample of a Population</b>

$$Sample (MAD)= \frac{1}{n -1} \sum \limits_{i=1}  ^{n}| x_i - \bar x $$
***


[1] Writing Matimatical Formulas in Markdown: https://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/
***
[2] Explanation for Mean Absolute Devation: https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/other-measures-of-spread/a/mean-absolute-deviation-mad-review
***
[3] Population and sample deviation review: https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-sample/a/population-and-sample-standard-deviation-review
***
[4] Population vs Sample data: http://mathbitsnotebook.com/Algebra1/StatisticsData/STPopSample.html
