# Tasks
***

These are my solutions to the Tasks assesment to be completed as part of my Emerging Technologies module. Author Keith Nolan.
Email: (g00351932@gmit.ie)

***

# Task 1


The first of these tasks is to write a Python function called sqrt2.
Thich calculates and prints to the screen the square root of 2 to 100 decimal places.
Below is my solution.


***

### Task: Calculate a sqaure root
***

The sqaure root of a number can be calculated using Newton's Method. [1]

To find the sqaure root $z$ of a number $x$, we can iterate using the following equation.

Add in how it works

$$ z' = z - \frac{z^2 - x}{2z} $$

[1] A tour of go. Exercise: Loops and Functions https://tour.golang.com/flowcontrol/8

def sqrt2(x):
    """ 
    function to calculate the sqaure root of 2 to 100 decimal places
    """
    #initial guess for the square root of z
    z = x / 2
    #loop until we're happy with the accuracy
    while abs(x -(z * z)) > 0.0001:
        #calculate a better guess for the square root
        z -= (z*z - x) / (2*z)
    #Return the approximate square root of 2
    
    return print("%.100f" % z)
#anwser = sqrt2(2)
#print("%100f" % result)

#### Testing the above function

#### Tesing the function on 2
Below the above function is being tested with some known values

In [16]:
#Test the above function on 2
sqrt2(2)

1.4142156862745098866440685014822520315647125244140625000000000000000000000000000000000000000000000000


In [17]:
import math
math.sqrt(2)

1.4142135623730951

In [43]:
import scipy.stats as stats

obs =[[90, 60, 104, 95], [30, 50, 51, 20],[30, 40, 45, 35]]

g, p, dof, expctd = chi2_contingency(obs)


#chi2_contingency(obs)
print(p)
print(dof)
print(g)
print(expctd)

0.0004098425861096696
6
24.5712028585826
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]


In [40]:
import numpy as np
import pandas as pd
import scipy.stats as stats

cols = ['A', 'B', 'C', 'D']
data = pd.DataFrame(columns=cols)

data.loc['White Collar'] = [90, 60, 104, 95]
data.loc['Blue Collar'] = [30, 50, 51, 20]
data.loc['No collar'] = [30, 40, 45, 35]

print (data)
V, p, dof, expected = stats.chi2_contingency(data) 

# add correction=False for uncorrected Chi-square
print ('P value for effect of area on proportion of each collar:')
print (p)
print ('\nExpected numbers if area did not effect proportion of each collar:')
print (expected)
print(dof)
print(V)

               A   B    C   D
White Collar  90  60  104  95
Blue Collar   30  50   51  20
No collar     30  40   45  35
P value for effect of area on proportion of each collar:
0.0004098425861096696

Expected numbers if area did not effect proportion of each collar:
[[ 80.53846154  80.53846154 107.38461538  80.53846154]
 [ 34.84615385  34.84615385  46.46153846  34.84615385]
 [ 34.61538462  34.61538462  46.15384615  34.61538462]]
6
24.5712028585826
